# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/pwm_layout.xdc

# Block Designs: bd/pwm_design/pwm_design.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pwm_design || ORIG_REF_NAME==pwm_design}]

# IP: bd/pwm_design/ip/pwm_design_processing_system7_0_1/pwm_design_processing_system7_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pwm_design_processing_system7_0_1 || ORIG_REF_NAME==pwm_design_processing_system7_0_1}]

# IP: bd/pwm_design/ip/pwm_design_pwm_core_0_1/pwm_design_pwm_core_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pwm_design_pwm_core_0_1 || ORIG_REF_NAME==pwm_design_pwm_core_0_1}]

# IP: bd/pwm_design/ip/pwm_design_ps7_0_axi_periph_1/pwm_design_ps7_0_axi_periph_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pwm_design_ps7_0_axi_periph_1 || ORIG_REF_NAME==pwm_design_ps7_0_axi_periph_1}]

# IP: bd/pwm_design/ip/pwm_design_rst_ps7_0_50M_0/pwm_design_rst_ps7_0_50M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pwm_design_rst_ps7_0_50M_0 || ORIG_REF_NAME==pwm_design_rst_ps7_0_50M_0}]

# IP: bd/pwm_design/ip/pwm_design_auto_pc_0/pwm_design_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pwm_design_auto_pc_0 || ORIG_REF_NAME==pwm_design_auto_pc_0}]

# XDC: bd/pwm_design/pwm_design_ooc.xdc
