# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {HDL-1065} -limit 10000
create_project -in_memory -part xc7z020clg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/VivadoProjects/custom_pwm_ip/custom_pwm_ip.cache/wt [current_project]
set_property parent.project_path D:/VivadoProjects/custom_pwm_ip/custom_pwm_ip.xpr [current_project]
set_property XPM_LIBRARIES XPM_CDC [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part em.avnet.com:zed:part0:1.3 [current_project]
set_property ip_repo_paths d:/VivadoProjects/ip_repo/pwm_core_1.0 [current_project]
set_property ip_output_repo d:/VivadoProjects/custom_pwm_ip/custom_pwm_ip.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib D:/VivadoProjects/custom_pwm_ip/custom_pwm_ip.srcs/sources_1/bd/pwm_design/hdl/pwm_design_wrapper.v
add_files D:/VivadoProjects/custom_pwm_ip/custom_pwm_ip.srcs/sources_1/bd/pwm_design/pwm_design.bd
set_property used_in_implementation false [get_files -all d:/VivadoProjects/custom_pwm_ip/custom_pwm_ip.srcs/sources_1/bd/pwm_design/ip/pwm_design_processing_system7_0_1/pwm_design_processing_system7_0_1.xdc]
set_property used_in_implementation false [get_files -all d:/VivadoProjects/custom_pwm_ip/custom_pwm_ip.srcs/sources_1/bd/pwm_design/ip/pwm_design_rst_ps7_0_50M_0/pwm_design_rst_ps7_0_50M_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/VivadoProjects/custom_pwm_ip/custom_pwm_ip.srcs/sources_1/bd/pwm_design/ip/pwm_design_rst_ps7_0_50M_0/pwm_design_rst_ps7_0_50M_0.xdc]
set_property used_in_implementation false [get_files -all d:/VivadoProjects/custom_pwm_ip/custom_pwm_ip.srcs/sources_1/bd/pwm_design/ip/pwm_design_rst_ps7_0_50M_0/pwm_design_rst_ps7_0_50M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/VivadoProjects/custom_pwm_ip/custom_pwm_ip.srcs/sources_1/bd/pwm_design/ip/pwm_design_auto_pc_0/pwm_design_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all D:/VivadoProjects/custom_pwm_ip/custom_pwm_ip.srcs/sources_1/bd/pwm_design/pwm_design_ooc.xdc]
set_property is_locked true [get_files D:/VivadoProjects/custom_pwm_ip/custom_pwm_ip.srcs/sources_1/bd/pwm_design/pwm_design.bd]

foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top pwm_design_wrapper -part xc7z020clg484-1


write_checkpoint -force -noxdef pwm_design_wrapper.dcp

catch { report_utilization -file pwm_design_wrapper_utilization_synth.rpt -pb pwm_design_wrapper_utilization_synth.pb }
