# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/VivadoProjects/custom_pwm_ip/custom_pwm_ip.srcs/sources_1/bd/pwm_design/ip/pwm_design_processing_system7_0_1/pwm_design_processing_system7_0_1.xci
# IP: The module: 'pwm_design_processing_system7_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/VivadoProjects/custom_pwm_ip/custom_pwm_ip.srcs/sources_1/bd/pwm_design/ip/pwm_design_processing_system7_0_1/pwm_design_processing_system7_0_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'pwm_design_processing_system7_0_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst]

# IP: d:/VivadoProjects/custom_pwm_ip/custom_pwm_ip.srcs/sources_1/bd/pwm_design/ip/pwm_design_processing_system7_0_1/pwm_design_processing_system7_0_1.xci
# IP: The module: 'pwm_design_processing_system7_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/VivadoProjects/custom_pwm_ip/custom_pwm_ip.srcs/sources_1/bd/pwm_design/ip/pwm_design_processing_system7_0_1/pwm_design_processing_system7_0_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'pwm_design_processing_system7_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]
